var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                             xxxxx  xxxx   xxx   xxxxx                          ",
   "                               x    x     x        x                            ",
   "                               x    xxxx   xxx     x                            ",
   "                               x    x         x    x                            ",
   "                               x    xxxx   xxx     x                            ",
   "                                                                                ",
   "                         ^ o                                      xxx           ",
   "                      xxxxx                         xx      xx   xx!xx          ",
   "                     x                                           x!!!x          ",
   "                    ox              o                            xx!xx          ",
   "                   xxxx      p     xxxxx                          xvx           ",
   "                   xxxxx     xxxxxx                                         xx  ",
   "  xx           x      mx                                                     x  ",
   "  x            xxxxxxxxx                 xxxxxxxxxxx                         x  ",
   "  x            x                                       xxxxxxxxx             x  ",
   "  x        xxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!      o           x  ",
   "  x  @     x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!   xxxxx  m    x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!xxxxxxxxxxxxxxxxxxxx!!!!!xxxxxxx   xxxxxxxxx  ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              xxxxx                  xxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],
  ["    xxx      xxx  xxx   xxx    xxx      xxx       xxx                 xxx        ",
   "    xxx      xxx  xxx   xxx    xxx      xxx       xxx                 xxx        ",
   "    xxx      xxx  xxx   xxx    xxx      xxx       xxx                 xxx        ",
   "    xxx      xxx  xxx   xxx    xxx      xxx       xxx   xxxxx         xxx        ",
   "    xxx      xxx  xxx   xxx    xxx      xxx       xxx                 xxx        ",
   "    xxx      xxx  xxx   xxx    xxx      xxx       xxx                 xxx        ",
   "    xxx      xxx  xxx   xxx    xxx      xxx       xxx                 xxx        ",
   "    xxx      xxx  xxx   xxx    xxx      xxx       xxx                 xxx        ",
   "    xxx      xxx  xxx   xxx    xxx      xxx       xxx   |||||         xxx        ",
   "    xxx      xxx  xxx   xxx    xxx      xxx       xxx                 xxx        ",
   "    xxx      xxx  xxx   xxx    xxx      xxx       xxx                 xxx        ",
   "    xxx      xxx  xxx   xxx    xxx      xxx                           xxx        ",
   "    xxx      xxx  xxx   xxx                                           xxx        ",
   "    xxx      xxx  xxx   xxx                                     ooo   xxx        ",
   "    xxx      xxx  xxx                                           xxxxxxxxx        ",
   "    xxx      xxx  xxx                             xxx   xxxxx         xxx        ",
   "             xxx               xxx      xxx       xxx                 xxx        ",
   "                               xxx      xxx       xxx                 xxx        ",
   "                        xxx    xxx      xxx       xxx                 xxx        ",
   "     @                  xxx    xxx      xxx       xxx                 xxx        ",
   "  xxxxx           xxx   xxx    xxx      xxx       xxx                 xxx        ",
   "    x x    xxxxx  xxx   xxx    xxx      xxx       xxx                 xxx        ",
   "!!!!x x!!!!!!xxx!!xxx!!!xxx!!!!xxx!!!!!!xxx!!!!!!!xxx!!!!!!!!!!!!!!!!!xxx        ",
   "!!!!x x!!!!!!xxx!!xxx!!!xxx!!!!xxx!!!!!!xxx!!!!!!!xxx!!!!!!!!!!!!!!!!!xxx        ",
   "!!!!x x!!!!!!xxx!!xxx!!!xxx!!!!xxx!!!!!!xxx!!!!!!!xxx!!!!!!!!!!!!!!!!!xxx        ",
   "!!!!x x!!!!!!xxx!!xxx!!!xxx!!!!xxx!!!!!!xxx!!!!!!!xxx!!!!!!!!!!!!!!!!!xxx        ",
   "!!!!x x!!!!!!xxx!!xxx!!!xxx!!!!xxx!!!!!!xxx!!!!!!!xxx!!!!!!!!!!!!!!!!!xxx        ",
   "!!!!x x!!!!!!xxx!!xxx!!!xxx!!!!xxx!!!!!!xxx!!!!!!!xxx!!!!!!!!!!!!!!!!!xxx        ",
   "!!!!x x!!!!!!xxx!!xxx!!!xxx!!!!xxx!!!!!!xxx!!!!!!!xxx!!!!!!!!!!!!!!!!!xxx        "], 
  ["                                                                                                                                 ",
	"                                                                                                                                ",
	"                                                                                                                                ",
	"                                                                                                                                ",
	"                xxxxxxx   xxxxxxx           xxxxxxx  xxxxxxx   xxxxxxx            xxxxxxxxxxxxxxxxxxxxxxxxxxxx                  ",
	"                |||||||                     |||||||                               ||||||||||||||||||||||||||||                  ",
	"                                                                                                                                ",
	"                                                                                                                                ",
	" x                                                                                                                       x      ",
	" x                                                             |||||||                                                   x      ",
	" x                                                                                                                       x      ",
	" x                                                                                                                       x      ",
	" x   @                                                                                                                   x      ",
	" xxxxxxxxxxxx                                                                                                            x      ",
	"                          |||||||                    |||||||                         ^                                  ox      ",
	"                xxxxxxx   xxxxxxx  xxxxxxx  xxxxxxx  xxxxxxx   xxxxxxx   xxxxxxx  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx   xxxxxxxx      ",
	"                                                                                                                                ",
	"!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
	"!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
	"!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
	"!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
	"!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
	"!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
	"!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
	"!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                                                                                                 "],
  ["                                                                                                                                   ",
  "x                                                                                                                                x  ",
  "x                                                                                                                                x  ",
  "x                                                                                                                                x  ",
  "x                                                                                                                                x  ",
  "x                                                                                                                                x  ",
  "x                                                                                                                                x  ",
  "x                                                                                                                                x  ",
  "x                                                                                                                                x  ",
  "x         @                                                                                                                      x  ",
  "xxxxxxxxxxxxx                                                                                                                    x  ",
  "x                                                                                                                                x  ",
  "x                             o                  o                          o                                                    x  ",
  "x                             x                  x                          x                                           o        x  ",
  "x                             x                  x                          x                                           x        x  ",
  "x   m         m             m x     m      m     x    m    m        m       x   m         m         m            m      x    m   x  ",
  "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
  "                                                                                                                                    ",
  "                                                                                                                                    ",
  "                                                                                                                                    "],
 ["                                                                                                                               ",
 "          o           o          o                                                                            o         o       ",
 "            o       o         o     o        o         o           o                   o          o           o         o       ",
 "              o   o         o          o     o         o            o                 o       o       o       o o       o       ",
 "                o         o              o   o         o             o       o       o      o           o     o  o      o       ",
 "                o         o              o   o         o              o     o o     o      o             o    o   o     o       ",
 "                o         o              o   o         o               o   o   o   o       o             o    o    o    o       ",
 "                o           o          o     o         o                o o     o o        o             o    o     o   o       ",
 "                o             o     o          o      o                  o       o          o           o     o      o  o       ",
 "                o                o               o o o                                        o        o      o       o o       ",
 "                                                                                                o o o                           ",
 "   @                                                                                                                            ",
 "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "                                                                                                                               "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
